# Site settings
title: martingalemeasure
email:
description: > # this means to ignore newlines until "baseurl:"
  The blog of Jeffrey Rosenbluth. Exploring computer science and
  mathematics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyrosenbluth.github.io" # the base hostname & protocol for your site
twitter_username: JeffRosenbluth
github_username:  jeffreyrosenbluth

# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

google_analytics: UA-62029615-1
